name: CI/CD Pipeline

on:
  push:
    branches: [main, dev-environment]
  pull_request:
    branches: [main, dev-environment]

env:
  CI: true

jobs:
  test-and-build:
    name: Test and Build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false --passWithNoTests

      - name: Build project
        run: npm run build
        env:
          CI: false

      - name: Verify build artifacts
        run: |
          echo "Build completed successfully"
          dir build/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/

  deploy-to-azure:
    name: Deploy to Azure Web App
    if: github.ref == 'refs/heads/main'
    needs: test-and-build
    runs-on: windows-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
